### ISSUE TITLE
Make well delivery start model

### ISSUE THREAD

**Issue by einarlandre** [Kavca/osdu-akm-models#9]
<img width="1385" alt="Screenshot 2022-12-08 at 13 12 40" src="https://user-images.githubusercontent.com/61762185/206443778-d5ff2fdb-dc4e-4008-b014-80d45a88495f.png">

Denne modellen illustreer relasjonene til et wellbore under design og construksjon

**Comment by SnorreFossland** [comment]
Fra Einar:

[modeller.pdf](https://github.com/Kavca/osdu-akm-models/files/10208260/modeller.pdf)

**Comment by franklillehagen** [comment]
This is a good start, but we must look closer at Wellbore Product Modelling to support all roles involved in Wellbore Product Planning, Design, Testing, Management and Drilling, and Production and Delivery Control tasks.

**Comment by franklillehagen** [comment]
The Collaborative POPS development of Product, Organization, Project (Process) and OSDU Platform (System) Modelling will require Project Roles of teams and single performers (humans and machines) as described by Snorre / Chat GPT.
